In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

For the posts without filtering for keywords (they are used just to see how many posts can be scraped in total with each query):
All post scrapable from each Developers subbreddit
Extracted 250 posts from programming subreddit
Extracted 248 posts from coding subreddit
Extracted 249 posts from computerscience subreddit

All post scrapable from each Designers subbreddit
Extracted 250 posts from design subreddit
Extracted 250 posts from graphic_design subreddit
Extracted 250 posts from graphicdesigning subreddit

For the posts with filtering (the post which we could actually use):
Filtered post scrapable from each Developers subbreddit
Extracted 74 posts from programming subreddit
Extracted 13 posts from coding subreddit
Extracted 45 posts from computerscience subreddit

Filtered post scrapable from each Designers subbreddit
Extracted 34 posts from design subreddit
Extracted 65 posts from graphic_design subreddit
Extracted 72 posts from graphicdesigning subreddit

Finally, I tried to extract from the available filtered post all the comments (without keyword filtering) just to get an idea of the amount of data:
Comments scrapable from each Developers subbreddit
Number of comments extracted for programming: 22966
Number of comments extracted for coding: 73
Number of comments extracted for computerscience: 2131

Comments scrapable from each Designers subbreddit
Number of comments extracted for design: 3843
Number of comments extracted for graphic_design: 10941
Number of comments extracted for graphicdesigning: 2016

# From 01/01/2020 to 31/12/2024 (comments + posts)
Keywords used for datasets: " AI ", " chatgpt ", " chat gpt "

## Quantities

	Programmers (comments)
		coding            = 668				(of 107'637)
		computerscience	  = 2'837			(of 289'786)
		programming       = 25'256		(of 8'056'545)
		--------------------------------------------
		TOT               = 28'761

	Designers (comments)
		Design            = 3'287			(of 825'195)
		GraphicDesigning  =	323				(of 26'408)
		graphic_design    = 18'814		(of 1'738'786)
		--------------------------------------------
		TOT               = 22'424

    TOT_DATA = 51'185


## CSV Structure
In the CSV files, we have that the columns are:
- for comments
  ```
  upvotes,date,user,link,content
  ```
- for posts
  ```
  upvotes,date,title,user,link,content
  ```

PROBLEM: the content can be only a link in posts, even if the post has textual parts after it. It is probably solvable if posts are filtered.

# Comments

Keywords used for filters: "job", "work", "profession", "career"

    Programmers   25942   ->  7761
    Designers     21727   ->  9206
    ---------------------------------
    Total         47669   ->  16967

In [5]:
def filter_comments(comments, keywords):
  dataframe = None
  # filter comments by keywords
  for k in keywords:
    f_comments = comments.loc[comments['content'].str.contains(k)]
    #print(f"{f_comments.shape} \t-> {k}")
    if dataframe is None:
      dataframe = f_comments
    else:
      dataframe = pd.concat([dataframe, f_comments])

  dataframe = dataframe.drop_duplicates()
  return dataframe

## On all comments combined

In [6]:
# obtain comments
comments = pd.DataFrame(pd.read_csv('comments.csv'))

comments

,upvotes,date,user,link,content
0,1,2020-01-01,u/[deleted],https://www.reddit.com/r/programming/comments/...,"Hmm, there seems to be a misunderstanding. You..."
1,18,2020-01-02,u/Frystix,https://www.reddit.com/r/programming/comments/...,Youtube likes to show you only some of your su...
2,2,2020-01-02,u/bartturner,https://www.reddit.com/r/programming/comments/...,So far Google has really not been willing to h...
3,10,2020-01-02,u/Magnesus,https://www.reddit.com/r/programming/comments/...,But they are predicting your moves with AI to ...
4,1,2020-01-02,u/socratic_bloviator,https://www.reddit.com/r/programming/comments/...,That's fair. But I think that machine code is...
...,...,...,...,...,...
47664,1,2024-12-28,u/Aneeq-CopyNinja,https://www.reddit.com/r/GraphicDesigning/comm...,"Yes sure, you see all those things which the A..."
47665,-4,2024-12-29,u/ShelterOver990,https://www.reddit.com/r/GraphicDesigning/comm...,No its Not Totally AI ! \nI have use AI fot g...
47666,1,2024-12-29,u/Mikaeladraws,https://www.reddit.com/r/GraphicDesigning/comm...,You described it as sophisticated in your head...
47667,1,2024-12-30,u/Designer-Board9276,https://www.reddit.com/r/GraphicDesigning/comm...,"If you are familiar with a bit of html, css an..."
47668,5,2024-12-31,u/manni-23,https://www.reddit.com/r/GraphicDesigning/comm...,Anyone who uses Ai for their final product in ...

In [7]:
keywords = ['job', 'work', 'profession', 'career']
filtered_comments = filter_comments(comments, keywords)

filtered_comments.to_csv('filtered_comments.csv', index=False) # export to csv
filtered_comments

,upvotes,date,user,link,content
8,1,2020-01-04,u/Kingmannie,https://www.reddit.com/r/programming/comments/...,"Why do anything anymore if AI and the ""Singula..."
26,5,2020-01-13,u/Multipoptart,https://www.reddit.com/r/programming/comments/...,20 years ago you bought a new book every month...
44,2,2020-01-23,u/shevy-ruby,https://www.reddit.com/r/programming/comments/...,&gt; The year is 2029. The Skynet artificial i...
51,5,2020-01-24,u/Multipoptart,https://www.reddit.com/r/programming/comments/...,Yep. \nMy company has been focusing hard on AI...
94,-8,2020-02-08,u/shevy-ruby,https://www.reddit.com/r/programming/comments/...,&gt; It’s not an unfamiliar experience today t...
...,...,...,...,...,...
47085,11,2024-12-22,u/UncannyFox,https://www.reddit.com/r/graphic_design/commen...,Their entire branding is made to attract begin...
47276,1,2024-12-28,u/helloflytrap,https://www.reddit.com/r/graphic_design/commen...,A few things to think about.\n1. It’s not loca...
47400,2,2023-01-21,u/Sym_design,https://www.reddit.com/r/GraphicDesigning/comm...,I'm in college for graphic design after leavin...
47438,1,2023-10-14,u/nickclaure,https://www.reddit.com/r/GraphicDesigning/comm...,If you want to take it serious and I hope you ...
47617,1,2024-11-28,u/Capital_T_Tech,https://www.reddit.com/r/GraphicDesigning/comm...,"YouTube tutorials, Benny Productions, Piximper..."

## On compsci comments

In [8]:
# obtain comments on compsci
comments_compsci = pd.DataFrame(pd.read_csv('comments_compsci.csv'))

comments_compsci

,upvotes,date,user,link,content
0,1,2020-01-01,u/[deleted],https://www.reddit.com/r/programming/comments/...,"Hmm, there seems to be a misunderstanding. You..."
1,18,2020-01-02,u/Frystix,https://www.reddit.com/r/programming/comments/...,Youtube likes to show you only some of your su...
2,2,2020-01-02,u/bartturner,https://www.reddit.com/r/programming/comments/...,So far Google has really not been willing to h...
3,10,2020-01-02,u/Magnesus,https://www.reddit.com/r/programming/comments/...,But they are predicting your moves with AI to ...
4,1,2020-01-02,u/socratic_bloviator,https://www.reddit.com/r/programming/comments/...,That's fair. But I think that machine code is...
...,...,...,...,...,...
25937,1,2024-12-23,u/IssacImmarel,https://www.reddit.com/r/computerscience/comme...,I have ADHD and did terribly on homework (by t...
25938,1,2024-12-25,u/time_2_live,https://www.reddit.com/r/computerscience/comme...,"Howdy!\nI’m not a software engineer, computer ..."
25939,1,2024-12-26,u/Select_Notice_843,https://www.reddit.com/r/computerscience/comme...,"thats a pretty good idea, its kind of rss read..."
25940,2,2024-12-27,u/TesttubeStandard,https://www.reddit.com/r/computerscience/comme...,It is more of a philosophical question I think...
25941,1,2024-12-30,u/BigTempsy,https://www.reddit.com/r/computerscience/comme...,AI has definitely been taken to the next level...

In [9]:
keywords = ['job', 'work', 'profession', 'career']
filtered_comments_compsci = filter_comments(comments_compsci, keywords)

filtered_comments_compsci.to_csv('filtered_comments_compsci.csv', index=False) # export to csv
filtered_comments_compsci

,upvotes,date,user,link,content
8,1,2020-01-04,u/Kingmannie,https://www.reddit.com/r/programming/comments/...,"Why do anything anymore if AI and the ""Singula..."
26,5,2020-01-13,u/Multipoptart,https://www.reddit.com/r/programming/comments/...,20 years ago you bought a new book every month...
44,2,2020-01-23,u/shevy-ruby,https://www.reddit.com/r/programming/comments/...,&gt; The year is 2029. The Skynet artificial i...
51,5,2020-01-24,u/Multipoptart,https://www.reddit.com/r/programming/comments/...,Yep. \nMy company has been focusing hard on AI...
94,-8,2020-02-08,u/shevy-ruby,https://www.reddit.com/r/programming/comments/...,&gt; It’s not an unfamiliar experience today t...
...,...,...,...,...,...
25605,1,2024-07-28,u/computerscience-ModTeam,https://www.reddit.com/r/computerscience/comme...,"Unfortunately, your post has been removed for ..."
25629,1,2024-08-08,u/redditlurkin69,https://www.reddit.com/r/computerscience/comme...,I agree :) it's very uninteresting to me. Appl...
25664,1,2024-08-27,u/JacksReditAccount,https://www.reddit.com/r/computerscience/comme...,I just read that there's a huge shortage of ac...
25797,1,2024-10-28,u/Educational-Horse604,https://www.reddit.com/r/computerscience/comme...,Tbh discrete math is really fun to learn. When...
25876,4,2024-12-01,u/Magdaki,https://www.reddit.com/r/computerscience/comme...,Generally you want the following:\n\- Introduc...

## On design comments

In [10]:
# obtain comments on design
comments_design = pd.DataFrame(pd.read_csv('comments_design.csv'))

comments_design

,upvotes,date,user,link,content
0,11,2020-01-05,u/RvYeri1,https://www.reddit.com/r/Design/comments/eki6y...,Trying to capture the elements of 80s Salsa al...
1,55,2020-01-07,u/RvYeri1,https://www.reddit.com/r/Design/comments/elhtp...,The design is a recreation of the album cover ...
2,1,2020-01-08,u/sugargliderpartytime,https://www.reddit.com/r/Design/comments/elhtp...,Nice work! Any Ai secrets you want to share?
3,1,2020-03-01,u/jokubaitisd,https://www.reddit.com/r/Design/comments/fb864...,https://ibb.co/m6cRMcj how AI sees this design.
4,8,2020-03-04,u/DwarfTheMike,https://www.reddit.com/r/Design/comments/fdch6...,I simply cannot use photoshop alone. While I s...
...,...,...,...,...,...
21722,1,2024-12-28,u/Aneeq-CopyNinja,https://www.reddit.com/r/GraphicDesigning/comm...,"Yes sure, you see all those things which the A..."
21723,-4,2024-12-29,u/ShelterOver990,https://www.reddit.com/r/GraphicDesigning/comm...,No its Not Totally AI ! \nI have use AI fot g...
21724,1,2024-12-29,u/Mikaeladraws,https://www.reddit.com/r/GraphicDesigning/comm...,You described it as sophisticated in your head...
21725,1,2024-12-30,u/Designer-Board9276,https://www.reddit.com/r/GraphicDesigning/comm...,"If you are familiar with a bit of html, css an..."
21726,5,2024-12-31,u/manni-23,https://www.reddit.com/r/GraphicDesigning/comm...,Anyone who uses Ai for their final product in ...

In [11]:
keywords = ['job', 'work', 'profession', 'career']
filtered_comments_design = filter_comments(comments_design, keywords)

filtered_comments_design.to_csv('filtered_comments_design.csv', index=False) # export to csv
filtered_comments_design

,upvotes,date,user,link,content
27,2,2020-09-04,u/moreexclamationmarks,https://www.reddit.com/r/Design/comments/imgdm...,I don't even think it's the top of the curve t...
33,1,2020-11-23,u/Glynn_a,https://www.reddit.com/r/Design/comments/jz6j2...,You don’t really need to hand them anything ex...
51,1,2021-04-14,u/madmanbumandangel,https://www.reddit.com/r/Design/comments/mqfha...,Motion design in the film /commercial busines...
78,2,2021-07-20,u/rwbronco,https://www.reddit.com/r/Design/comments/on670...,I don't think you'll be losing your job to AI....
85,17,2021-09-11,u/brron,https://www.reddit.com/r/Design/comments/pm4r9...,"These are great if you freelance or dabble, bu..."
...,...,...,...,...,...
21143,11,2024-12-22,u/UncannyFox,https://www.reddit.com/r/graphic_design/commen...,Their entire branding is made to attract begin...
21334,1,2024-12-28,u/helloflytrap,https://www.reddit.com/r/graphic_design/commen...,A few things to think about.\n1. It’s not loca...
21458,2,2023-01-21,u/Sym_design,https://www.reddit.com/r/GraphicDesigning/comm...,I'm in college for graphic design after leavin...
21496,1,2023-10-14,u/nickclaure,https://www.reddit.com/r/GraphicDesigning/comm...,If you want to take it serious and I hope you ...
21675,1,2024-11-28,u/Capital_T_Tech,https://www.reddit.com/r/GraphicDesigning/comm...,"YouTube tutorials, Benny Productions, Piximper..."

## Filtered in between two dates (from filtered)

From 01-10-2022 to 31-03-2023

In [12]:
from_date = datetime.strptime("2022-10-01", "%Y-%m-%d")
to_date = datetime.strptime("2023-03-31", "%Y-%m-%d")

def filter_df(dataframe, from_date, to_date):
  dataframe['date'] = pd.to_datetime(dataframe['date'], format='%Y-%m-%d')

  filtered_dataframe = dataframe.loc[(dataframe['date'] >= from_date) & (dataframe['date'] <= to_date)]

  return filtered_dataframe

In [13]:
filter_df(filtered_comments, from_date, to_date)

,upvotes,date,user,link,content
4399,2,2022-10-01,u/wetrorave,https://www.reddit.com/r/programming/comments/...,Hunter sounds a lot like David Attenborough.\n...
4435,2,2022-10-17,u/kmtrp,https://www.reddit.com/r/programming/comments/...,"Maybe today's tools are bad for edge cases, al..."
4437,-7,2022-10-18,u/ThatCrankyGuy,https://www.reddit.com/r/programming/comments/...,"For every advancement in AI, there are two din..."
4581,0,2022-10-27,u/ItsAllegorical,https://www.reddit.com/r/programming/comments/...,There is a ton of information out there. You c...
4611,7,2022-11-02,u/dotnet_enjoyer,https://www.reddit.com/r/programming/comments/...,There’s a weird paradox where people go from ‘...
...,...,...,...,...,...
32073,2,2023-03-07,u/BeeBladen,https://www.reddit.com/r/graphic_design/commen...,My immediate thoughts: \n1. Skills expectation...
32149,1,2023-03-21,u/nopixelsplz,https://www.reddit.com/r/graphic_design/commen...,If you consider yourself a creative person wit...
32235,1,2023-03-25,u/ruffazrats,https://www.reddit.com/r/graphic_design/commen...,I used to HATE canva. I found it very limiting...
32294,2,2023-03-30,u/iveroi,https://www.reddit.com/r/graphic_design/commen...,As a designer who only became his career less ...
47400,2,2023-01-21,u/Sym_design,https://www.reddit.com/r/GraphicDesigning/comm...,I'm in college for graphic design after leavin...

In [14]:
filter_df(filtered_comments_compsci, from_date, to_date)

,upvotes,date,user,link,content
4399,2,2022-10-01,u/wetrorave,https://www.reddit.com/r/programming/comments/...,Hunter sounds a lot like David Attenborough.\n...
4435,2,2022-10-17,u/kmtrp,https://www.reddit.com/r/programming/comments/...,"Maybe today's tools are bad for edge cases, al..."
4437,-7,2022-10-18,u/ThatCrankyGuy,https://www.reddit.com/r/programming/comments/...,"For every advancement in AI, there are two din..."
4581,0,2022-10-27,u/ItsAllegorical,https://www.reddit.com/r/programming/comments/...,There is a ton of information out there. You c...
4611,7,2022-11-02,u/dotnet_enjoyer,https://www.reddit.com/r/programming/comments/...,There’s a weird paradox where people go from ‘...
...,...,...,...,...,...
8166,3,2023-02-28,u/KevinCarbonara,https://www.reddit.com/r/programming/comments/...,"&gt; If you don't follow said rules, you would..."
8800,1,2023-03-21,u/nxqv,https://www.reddit.com/r/programming/comments/...,That's assuming we need the same number of pro...
9108,4,2023-03-28,u/jherico,https://www.reddit.com/r/programming/comments/...,Developers that use the tools are going to be ...
24393,14,2022-12-08,u/MpVpRb,https://www.reddit.com/r/computerscience/comme...,Tech is not about learning one thing in school...
24416,5,2022-12-14,u/harg0w,https://www.reddit.com/r/computerscience/comme...,if someone that does comsci for a career gets ...

In [15]:
filter_df(filtered_comments_design, from_date, to_date)

,upvotes,date,user,link,content
325,-4,2022-10-25,u/MoeHefin,https://www.reddit.com/r/Design/comments/yd1jz...,Get ahead of the curve! Learn to use the AI to...
332,5,2022-10-26,u/jtbruceart,https://www.reddit.com/r/Design/comments/yd1jz...,&gt; so u want the entire design community to ...
334,1,2022-10-26,u/50mm-f2,https://www.reddit.com/r/Design/comments/ydkby...,maybe it’s just me but I want AI to take all o...
335,1,2022-10-26,u/OokySpookums,https://www.reddit.com/r/Design/comments/yd1jz...,Let's make a scenario here.\nA company needs a...
336,1,2022-10-26,u/MoeHefin,https://www.reddit.com/r/Design/comments/yd1jz...,"Yes, 100% agreed :D\nThe issue I have with tha..."
...,...,...,...,...,...
6131,2,2023-03-07,u/BeeBladen,https://www.reddit.com/r/graphic_design/commen...,My immediate thoughts: \n1. Skills expectation...
6207,1,2023-03-21,u/nopixelsplz,https://www.reddit.com/r/graphic_design/commen...,If you consider yourself a creative person wit...
6293,1,2023-03-25,u/ruffazrats,https://www.reddit.com/r/graphic_design/commen...,I used to HATE canva. I found it very limiting...
6352,2,2023-03-30,u/iveroi,https://www.reddit.com/r/graphic_design/commen...,As a designer who only became his career less ...
21458,2,2023-01-21,u/Sym_design,https://www.reddit.com/r/GraphicDesigning/comm...,I'm in college for graphic design after leavin...

# Posts

Keywords used for filters: "job", "work", "profession", "career"

    Programmers   605     ->  196
    Designers     1685    ->  946
    ---------------------------------
    Total         2290    ->  1142

In [16]:
def filter_posts(posts, keywords):
  dataframe = None
  # filter posts by keywords
  for k in keywords:
    f_title = posts.loc[posts['title'].str.contains(k)]
    f_content = posts.loc[posts['content'].str.contains(k)]
    f_posts = pd.concat([f_title, f_content])
    #print(f"{f_posts.shape} \t-> {k}")

    if dataframe is None:
      dataframe = f_posts
    else:
      dataframe = pd.concat([dataframe, f_posts])

  dataframe = dataframe.drop_duplicates()
  return dataframe

## On all posts

In [17]:
# obtain posts
posts = pd.DataFrame(pd.read_csv('posts.csv'))

posts

,upvotes,date,title,user,link,content
0,0,2022-12-07,My take: gpt won't change a thing,u/SuddenTemperature233,https://www.reddit.com/r/programming/comments/...,https://towardsdatascience.com/gpt-3-or-any-ai...
1,0,2022-12-09,Is it worth starting coding now that open ai e...,u/Michaelyouareawesome,https://www.reddit.com/r/programming/comments/...,https://youtu.be/yIZqIMNvqjg
2,0,2022-12-18,A mini rant about ChatGPT,u/esmagik,https://www.reddit.com/r/programming/comments/...,https://images.app.goo.gl/DFRJKW522WvRkBhCA
3,0,2022-12-26,Chatty - التطبيقات على Google Play,u/abdulazeezraja,https://www.reddit.com/r/programming/comments/...,https://play.google.com/store/apps/details?id=...
4,0,2023-01-01,Could Roko's basilisk code itself?,u/workandlearn,https://www.reddit.com/r/programming/comments/...,https://en.m.wikipedia.org/wiki/Roko%27s_basilisk
...,...,...,...,...,...,...
2285,1,2024-12-30,Do you think that AI will replace us graphic d...,u/Top_Procedure_3322,https://www.reddit.com/r/graphic_design/commen...,Specially how our AI now can create videos and...
2286,1,2024-12-30,Do you think AI will replace us graphic design...,u/Top_Procedure_3322,https://www.reddit.com/r/graphic_design/commen...,"I do think it won’t but, this probably what mo..."
2287,1,2024-12-30,Is this how it will be ?,u/hwy320,https://www.reddit.com/r/graphic_design/commen...,I stayed at Comfort inn in Ft Myers and saw th...
2288,139,2024-12-31,Lidl Protein Powder AI,u/shen-ani-gans,https://www.reddit.com/r/graphic_design/commen...,https://www.reddit.com/gallery/1hqgbb5
2289,98,2024-12-31,I'm having trouble finding a competent graphic...,u/kraci_,https://www.reddit.com/r/graphic_design/commen...,I recently formed a new (and my very first) co...

In [18]:
keywords = ['job', 'work', 'profession', 'career']
filtered_posts = filter_posts(posts, keywords)

filtered_posts.to_csv('filtered_posts.csv', index=False) # export to csv
filtered_posts

,upvotes,date,title,user,link,content
29,0,2023-06-03,When ChatGPT takes jobs one by one,u/Available-Bass-7575,https://www.reddit.com/r/programming/comments/...,https://youtu.be/mHXojRyXtIU
93,1,2023-12-05,How hard is it really to learn a job? I never ...,u/Existing_Toe4234,https://www.reddit.com/r/programming/comments/...,https://google.com
95,1,2023-12-07,AI will not take programmer’s job,u/AdventurousAct8431,https://www.reddit.com/r/programming/comments/...,http://google.com
111,1,2024-01-03,AI is overhyped - Why we still will have jobs ...,u/vik76,https://www.reddit.com/r/programming/comments/...,https://youtu.be/R55fwyAiF-0?si=swGwqtO-7aFD7Xyl
124,1,2024-02-19,Need a Suggestion about job,u/Good_Entry_2389,https://www.reddit.com/r/programming/comments/...,http://GitHub.com
...,...,...,...,...,...,...
2043,2,2024-09-04,Why AI Isn’t Going to Make Art...,u/brianlucid,https://www.reddit.com/r/graphic_design/commen...,Hi. For those of you concerned over AI and its...
2044,31,2024-09-04,Why AI is Not Going to Make Art...,u/brianlucid,https://www.reddit.com/r/graphic_design/commen...,Hi. For those of you concerned about AI and it...
2049,1,2024-09-06,Is there a future in graphic design?,u/cheesecurdpeen,https://www.reddit.com/r/graphic_design/commen...,"Hi everyone. New to this sub, but I’ve been a ..."
2110,40,2024-10-11,Is anyone else old enough to remember…?,u/SuspiciousBee7257,https://www.reddit.com/r/graphic_design/commen...,This year I realized I’ve been doing this for ...
2146,1,2024-10-25,Can’t Draw? Don’t Bother.,u/CandidLeg8036,https://www.reddit.com/r/graphic_design/commen...,The landscape of Graphic Design has evolved an...

## On compsci posts

In [19]:
# obtain posts on compsci
posts_compsci = pd.DataFrame(pd.read_csv('posts_compsci.csv'))

posts_compsci

,upvotes,date,title,user,link,content
0,0,2022-12-07,My take: gpt won't change a thing,u/SuddenTemperature233,https://www.reddit.com/r/programming/comments/...,https://towardsdatascience.com/gpt-3-or-any-ai...
1,0,2022-12-09,Is it worth starting coding now that open ai e...,u/Michaelyouareawesome,https://www.reddit.com/r/programming/comments/...,https://youtu.be/yIZqIMNvqjg
2,0,2022-12-18,A mini rant about ChatGPT,u/esmagik,https://www.reddit.com/r/programming/comments/...,https://images.app.goo.gl/DFRJKW522WvRkBhCA
3,0,2022-12-26,Chatty - التطبيقات على Google Play,u/abdulazeezraja,https://www.reddit.com/r/programming/comments/...,https://play.google.com/store/apps/details?id=...
4,0,2023-01-01,Could Roko's basilisk code itself?,u/workandlearn,https://www.reddit.com/r/programming/comments/...,https://en.m.wikipedia.org/wiki/Roko%27s_basilisk
...,...,...,...,...,...,...
600,1,2024-08-12,I USED AI TO AUTOMATICALLY APPLY FOR 1000 JOBS...,u/Wooden-Elevator-1421,https://www.reddit.com/r/computerscience/comme...,\n# How Did I Do It?\nI created an AI bot that...
601,1,2024-11-10,FUTURE OF CS,u/nature_is_fab,https://www.reddit.com/r/computerscience/comme...,I am pursuing my bachelor's in computer Scienc...
602,1,2024-12-03,“Is learning in AI and Prompt Engineering Cert...,u/Pitiful-Box6092,https://www.reddit.com/r/computerscience/comme...,"Recently, I’ve been seeing numerous posts and ..."
603,1,2024-12-15,choosing major,u/ghiolimer,https://www.reddit.com/r/computerscience/comme...,im a hs student and i want to focus on ai. i w...
604,1,2024-12-18,Help,u/permboy102,https://www.reddit.com/r/computerscience/comme...,"Hello, I’m currently a junior in college and I..."

In [20]:
keywords = ['job', 'work', 'profession', 'career']
filtered_posts_compsci = filter_posts(posts_compsci, keywords)

filtered_posts_compsci.to_csv('filtered_posts_compsci.csv', index=False) # export to csv
filtered_posts_compsci

,upvotes,date,title,user,link,content
29,0,2023-06-03,When ChatGPT takes jobs one by one,u/Available-Bass-7575,https://www.reddit.com/r/programming/comments/...,https://youtu.be/mHXojRyXtIU
93,1,2023-12-05,How hard is it really to learn a job? I never ...,u/Existing_Toe4234,https://www.reddit.com/r/programming/comments/...,https://google.com
95,1,2023-12-07,AI will not take programmer’s job,u/AdventurousAct8431,https://www.reddit.com/r/programming/comments/...,http://google.com
111,1,2024-01-03,AI is overhyped - Why we still will have jobs ...,u/vik76,https://www.reddit.com/r/programming/comments/...,https://youtu.be/R55fwyAiF-0?si=swGwqtO-7aFD7Xyl
124,1,2024-02-19,Need a Suggestion about job,u/Good_Entry_2389,https://www.reddit.com/r/programming/comments/...,http://GitHub.com
...,...,...,...,...,...,...
491,1,2024-03-21,Is pursuing computer science still worth it in...,u/Marvelous_Axel,https://www.reddit.com/r/computerscience/comme...,Hey guys i am a university student studying CS...
516,1,2024-04-27,Will AI Replace SWE?,u/Any_Volume5771,https://www.reddit.com/r/computerscience/comme...,"Hi All,\nI'm interested in a career in SWE, bu..."
530,2,2024-05-09,Do I need a GPU for AI/ML?,u/me_is_Anonymous_,https://www.reddit.com/r/computerscience/comme...,"I'm currently a grade 12 student, going to col..."
533,1,2024-05-16,AI Rant/ Reassurance,u/RemoniQue,https://www.reddit.com/r/computerscience/comme...,It's 5am and I haven't slept a bit because I'v...
557,1,2024-06-07,What's Reasoned programming?,u/leao_26,https://www.reddit.com/r/computerscience/comme...,I mean it's first time I saw a whole book on i...

## On design posts

In [21]:
# obtain posts on design
posts_design = pd.DataFrame(pd.read_csv('posts_design.csv'))

posts_design

,upvotes,date,title,user,link,content
0,2,2020-02-05,File format,u/Love_Each_Other_3000,https://www.reddit.com/r/GraphicDesigning/comm...,"Hello, I am planning on making art with a logo..."
1,1,2020-03-20,Jpeg to Ai format convert,u/ilike2show22m,https://www.reddit.com/r/GraphicDesigning/comm...,"Hi guys,\nI'm new and wondering how you can co..."
2,1,2021-11-16,Templates for graphics used in federal project...,u/Prestigious_Solid_27,https://www.reddit.com/r/GraphicDesigning/comm...,Hi there— I’ve never done design for proposals...
3,2,2022-04-20,What on earth is Figma?,u/darkshark54,https://www.reddit.com/r/GraphicDesigning/comm...,"Hi all, I've been browsing for freelance gigs ..."
4,2,2022-05-11,Does anyone else have this issue?,u/DraftDesigns_,https://www.reddit.com/r/GraphicDesigning/comm...,I thought I was being smart by finally purchas...
...,...,...,...,...,...,...
1680,1,2024-12-30,Do you think that AI will replace us graphic d...,u/Top_Procedure_3322,https://www.reddit.com/r/graphic_design/commen...,Specially how our AI now can create videos and...
1681,1,2024-12-30,Do you think AI will replace us graphic design...,u/Top_Procedure_3322,https://www.reddit.com/r/graphic_design/commen...,"I do think it won’t but, this probably what mo..."
1682,1,2024-12-30,Is this how it will be ?,u/hwy320,https://www.reddit.com/r/graphic_design/commen...,I stayed at Comfort inn in Ft Myers and saw th...
1683,139,2024-12-31,Lidl Protein Powder AI,u/shen-ani-gans,https://www.reddit.com/r/graphic_design/commen...,https://www.reddit.com/gallery/1hqgbb5
1684,98,2024-12-31,I'm having trouble finding a competent graphic...,u/kraci_,https://www.reddit.com/r/graphic_design/commen...,I recently formed a new (and my very first) co...

In [22]:
keywords = ['job', 'work', 'profession', 'career']
filtered_posts_design = filter_posts(posts_design, keywords)

filtered_posts_design.to_csv('filtered_posts_design.csv', index=False) # export to csv
filtered_posts_design

,upvotes,date,title,user,link,content
63,1,2024-11-01,Want to help my Girlfriend use recent tech adv...,u/SomeRedditDood,https://www.reddit.com/r/GraphicDesigning/comm...,"Hi all, my girlfriend is a graphic designer wh..."
110,0,2023-01-10,Help! AI stole my job!,u/FormlessMars,https://www.reddit.com/r/Design/comments/108gw...,Hey folks! \nSo I'm conducting research into t...
115,3,2023-01-24,Will graphic design jobs be replaced by robots...,u/vikas_agrawal77,https://www.reddit.com/r/Design/comments/10jzx...,This question is the elephant in the room for ...
126,1,2023-04-25,How do you see AI affecting the job market for...,u/Justagirl447,https://www.reddit.com/r/Design/comments/12yty...,How do you see AI affecting the job market for...
241,1,2024-04-10,Design jobs that pays well in NYC?,u/andyc2648,https://www.reddit.com/r/Design/comments/1c0d3...,"Hello, I’m currently a junior in college study..."
...,...,...,...,...,...,...
1438,2,2024-09-04,Why AI Isn’t Going to Make Art...,u/brianlucid,https://www.reddit.com/r/graphic_design/commen...,Hi. For those of you concerned over AI and its...
1439,31,2024-09-04,Why AI is Not Going to Make Art...,u/brianlucid,https://www.reddit.com/r/graphic_design/commen...,Hi. For those of you concerned about AI and it...
1444,1,2024-09-06,Is there a future in graphic design?,u/cheesecurdpeen,https://www.reddit.com/r/graphic_design/commen...,"Hi everyone. New to this sub, but I’ve been a ..."
1505,40,2024-10-11,Is anyone else old enough to remember…?,u/SuspiciousBee7257,https://www.reddit.com/r/graphic_design/commen...,This year I realized I’ve been doing this for ...
1541,1,2024-10-25,Can’t Draw? Don’t Bother.,u/CandidLeg8036,https://www.reddit.com/r/graphic_design/commen...,The landscape of Graphic Design has evolved an...

# Text cleaning

In [23]:
!pip install --quiet deep-translator
from deep_translator import GoogleTranslator
from tqdm.auto import tqdm
import nltk
nltk.download('punkt_tab')
from time import sleep

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 2.7 MB/s eta 0:00:00

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [24]:
def translate_comments(comments, language, language_token):
  gt = GoogleTranslator(source='auto', target=language)
  comments.reset_index(drop=True, inplace=True)

  # translate
  for i in tqdm(range(len(comments))):
    text = comments.loc[i,'content']
    token = nltk.sent_tokenize(text, language_token)
    comments.loc[i,'translated'] = None

    # to work around the limit of 5000 characters per request
    for tt in token:
      translated_text = gt.translate(tt)

      if comments.loc[i,'translated'] is None:
        comments.loc[i,'translated'] = translated_text
      elif translated_text is not None:
        comments.loc[i,'translated'] = comments.loc[i,'translated'] + translated_text

    # to work around the limit of 5 requests per second
    sleep(0.5)
  comments.dropna(inplace=True)

  return translated

In [27]:
translate_comments(comments, 'en', 'english')

  0%|          | 0/47669 [00:00<?, ?it/s]

KeyboardInterrupt: